<?php
error_reporting(E_ALL);
include("../../../php_includes/cmaster.inc");
require_once("../../../php_includes/FlashMessage.php");

function html_header() {
    echo "<html>\n<head>\n";
    echo "<title>CService enable two-step verification</title>\n";
    std_theme_styles();
    ?>
    <META HTTP-EQUIV="Pragma" CONTENT="no-cache">
                    <link rel="stylesheet" type="text/css" href="./css/smoothness/jquery-ui-1.8.20.custom.css" media="screen" />
    <link rel="stylesheet" type="text/css" href="./css/dialog-custom.css" media="screen" />
    <link rel="stylesheet" type="text/css" href="../css/flash.css" media="screen" />
    <script type="text/javascript" src="./js/jquery-1.7.2.min.js"~></script>
    <script type="text/javascript" src="./js/jquery-ui-1.8.20.custom.min.js"></script>
    <script type="text/javascript" src="./js/jquery.infieldlabel.min.js"></script>
    <script type="text/javascript" src="./js/custom.js"></script>
    </head>
    <?php
    std_theme_body("","document.forms[0].pin.focus();");
}

function ts_disable_form() {
    global $SECURE_ID;
    ?>
    <form class="totp" name="dis_totp" method="post" action="disable_totp.php">
      <input type="hidden" name="crc" value="<?= md5( $SECURE_ID . CRC_SALT_0011 ) ?>">
      <p>Enter the security code generated by your mobile authenticator app to disable two-step verification for your account.</p>
      <p>
        <label for="pin">6-digit code</label><br />
        <input type="text" name="pin" id="pin" placeholder="">
        <input type="submit" value=" Submit ">
      </p>
    </form>
    <?php
}

std_connect();
$user_id = std_security_chk($auth);
$cTheme = get_theme_info();

if ($user_id == 0 || $auth == "") {
    html_header();
    echo "<h3>You must be logged in to view this page!</h3></body></html>";
    die;
}

if (!session_id()) {
    session_start();
}

$flash = new FlashMessage();
$sqlresult = pg_safe_exec("SELECT * FROM users WHERE id='" . $user_id . "'");
$user_obj = pg_fetch_object($sqlresult, 0);
$authtok = explode(":", $auth);
$authcsc = $authtok[3];
$user_name = $authtok[0];
$SECURE_ID=md5( $user_id . CRC_SALT_0019 . $authcsc );

if(!has_totp($user_id)) {
    $flash->message("Your account does not yet have two-step verification enabled");
    header("Location: ../users.php?id={$user_id}");
    die;
} elseif (!empty($_POST) && $_POST['crc'] == md5($SECURE_ID . CRC_SALT_0011)) {
    $otp = filter_var($_POST['pin'], FILTER_SANITIZE_NUMBER_INT);
    echo $user_obj->totp;
    if (!ip_check_totp($user_name, 0)) {
        $flash->message("Too many failed two-step verification code attempts. Please try again in 24 hours.", "error");
        header("Location: ../users.php?id={$user_id}");
        die;
    } elseif (preg_match(NON_BOGUS_TOTP, trim($otp)) && Google2FA::verify_key($user_obj->totp_key, $otp)) {
        $flash->message("Two-step verification successfully disabled. You will no longer be asked for a 6-digit code when logging in.");
        disable_totp($user_obj->id);
        $query = "DELETE from ips where ipnum='" . cl_ip() . "' AND lower(user_name)='" .strtolower($user_obj->user_name) . "'";
        pg_exec($query);
        header("Location: ../users.php?id={$user_id}");
        die;
    } else {
        html_header();
        $flash->message("Invalid code, please try again!", "error");
        ip_check_totp($user_name, 1);
        echo $flash->show();
        echo "<h3>Disable two-step verification</h3>";
        ts_disable_form();
    }
} else {
    html_header();
    echo "<h3>Disable two-step verification</h3>";
    ts_disable_form();
}
?>
</body></html>